FROM mcr.microsoft.com/devcontainers/javascript-node

# Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# Uncomment if you want to install more global Node modules.
# RUN su node -c "npm install -g <your-package-list-here>"
