export type Error =
    | "name_missing"
    | "name_invalid"
    | "name_long"
    | "email_missing"
    | "email_invalid"
    | "email_long"
    | "email_taken"
    | "password_missing"
    | "password_invalid"
    | "password_short"
    | "password_long"
    | "password_confirm"
    | "confirmPassword_missing"
    | "confirmPassword_invalid";
